name: Run this workflow based on the approval comment in the issue
on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: rytswd/comvent@v0.1.0
        id: approvalid
        with:
          keyword: Approved # This is the regex string to match against
      - name: Run this even if comment did not match
        id: approvalStatus
        run: |
          echo Running this even without comment match
      - name: Run when comment contains matching string
        id: approvalStatus
        run: |
          echo Comment has the matching string
        if: steps.approvalid.outputs.comvent != ''