name: Approval Workflow Test
on: 
  issues:
    types: [closed]

jobs:
  PerformingDeployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run deployment command
      run: echo "Performing deployment"