name: Run this workflow based on the approval comment in the issue
on: issue_comment

jobs:
  comment:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{steps.approvalStatus.outputs.approval}}
    steps:
      - uses: rytswd/comvent@v0.1.0
        id: approvalid
        with:
          keyword: Approved # This is the regex string to match against
      - name: Run this even if comment did not match
        run: |
          echo Running this even without comment match
          exit 1
        if: steps.approvalid.outputs.comvent == ''
      - name: Run when comment contains matching string
        id: approvalStatus
        run: |
          echo Comment has the matching string
          echo "::set-output name=approval::TRUE"
        if: steps.approvalid.outputs.comvent != ''
  
  Deployment:
    needs: [comment]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Output from the Approval comment job
      run: echo ${{needs.comment.outputs.output1}}