
name: CI Workflow for CloudFoundry

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Create Issue Action
      uses: nashmaniac/create-issue-action@v1.1
      with:
        title: "Deploy Project - Sample Issue"
        token: ${{secrets.GITHUB_TOKEN}}
        labels: "None" 
        assignees: "srinivasaregeti" 
        body: "Approve the issue to proceed" 
    